/**
 * PROJECT_CONTENT_MODEL.ts
 *
 * SOURCE OF TRUTH for this specific project's content structure.
 * Generated by analyzing: apps/web/src/content/
 * Date: 2026-01-31
 *
 * This file documents the exact content collections and their fields.
 * All Sanity schemas, migration scripts, and transforms MUST match this structure.
 *
 * Collections discovered:
 * - team/ (10 files)
 * - store/ (6 files)
 * - gallery/ (10 files)
 * - posts/ (10 files)
 * - legal/ (1 file - privacy.md)
 */

export const PROJECT_COLLECTIONS = {
  team: {
    sanityType: "teamMember",
    folderPath: "apps/web/src/content/team",
    fileCount: 1,
    fields: {
      name: { type: "string", required: true },
      role: { type: "string", required: false },
      bio: { type: "string", required: false },
      image: {
        type: "image",
        required: true,
        structure: { url: "image()", alt: "string" },
      },
      socials: {
        type: "object",
        required: false,
        structure: {
          twitter: { type: "string", required: false },
          website: { type: "string", required: false },
          linkedin: { type: "string", required: false },
          email: { type: "string", required: false },
        },
      },
    },
    relationships: {},
  },

  store: {
    sanityType: "product",
    folderPath: "apps/web/src/content/store",
    fileCount: 1,
    fields: {
      title: { type: "string", required: true },
      price: { type: "string", required: true },
      checkout: { type: "string", required: true },
      license: { type: "string", required: true },
      description: { type: "string", required: true },
      highlights: {
        type: "array",
        required: true,
        of: "string",
      },
      specifications: {
        type: "array",
        required: false,
        of: { name: "string", value: "string" },
      },
      image: {
        type: "image",
        required: true,
        structure: { url: "image()", alt: "string" },
      },
      images: {
        type: "array",
        required: true,
        of: { url: "image()", alt: "string" },
      },
      faq: {
        type: "array",
        required: false,
        of: { question: "string", answer: "string" },
      },
    },
    relationships: {},
  },

  gallery: {
    sanityType: "gallery",
    folderPath: "apps/web/src/content/gallery",
    fileCount: 1,
    fields: {
      category: { type: "string", required: true },
      title: { type: "string", required: true },
      description: { type: "string", required: true },
      thumbnail: {
        type: "image",
        required: true,
        structure: { url: "image()", alt: "string" },
      },
      images: {
        type: "array",
        required: false,
        of: { url: "image()", alt: "string" },
      },
    },
    relationships: {},
  },

  posts: {
    sanityType: "post",
    folderPath: "apps/web/src/content/posts",
    fileCount: 1,
    fields: {
      title: { type: "string", required: true },
      pubDate: { type: "date", required: true },
      description: { type: "string", required: true },
      team: { type: "string", required: true }, // Reference to team member slug
      image: {
        type: "image",
        required: true,
        structure: { url: "image()", alt: "string" },
      },
      tags: {
        type: "array",
        required: true,
        of: "string",
      },
    },
    relationships: {
      team: {
        type: "reference",
        to: "team",
        description: "References team member by slug",
      },
    },
  },

  legal: {
    sanityType: "legalPage",
    folderPath: "apps/web/src/content/legal",
    fileCount: 1,
    fields: {
      page: { type: "string", required: true },
      pubDate: { type: "date", required: true },
    },
    relationships: {},
    notes: "Body content is markdown, converted to Portable Text in Sanity",
  },
} as const;

// =============================================================================
// DERIVED TYPES
// =============================================================================

export type CollectionName = keyof typeof PROJECT_COLLECTIONS;
export type SanityTypeName =
  (typeof PROJECT_COLLECTIONS)[CollectionName]["sanityType"];

// Field counts for validation
export const FIELD_COUNTS = {
  team: 5, // name, role, bio, image, socials
  store: 10, // title, price, checkout, license, description, highlights, specifications, image, images, faq
  gallery: 5, // category, title, description, thumbnail, images
  posts: 6, // title, pubDate, description, team, image, tags
  legal: 2, // page, pubDate (body is content, not frontmatter)
} as const;

// Schema count must equal collection count
export const EXPECTED_SCHEMA_COUNT = Object.keys(PROJECT_COLLECTIONS).length; // 5

// =============================================================================
// VALIDATION HELPERS
// =============================================================================

export function validateSchemaCount(actualCount: number): boolean {
  return actualCount === EXPECTED_SCHEMA_COUNT;
}

export function getCollectionConfig(name: CollectionName) {
  return PROJECT_COLLECTIONS[name];
}

export function getSanityTypeName(collectionName: CollectionName): string {
  return PROJECT_COLLECTIONS[collectionName].sanityType;
}
